baseURL: http://www.djpeacher.com/
languageCode: en-us
title: Jonathan Peacher
theme: simple-hugo
description: Software Engineer • Coffee Enthusiast • Dungeon Master • Cat Dad
copyright: All work licensed under CC BY-SA 4.0 unless otherwise stated.
params:
  title: Jonathan Peacher
  subtitle:
    Software Engineer • Coffee Enthusiast • Dungeon Master • Cat Dad<br><small><a href="https://twitter.com/_djpeacher">Twitter</a> • <a href="https://fosstodon.org/@djpeacher">Mastadon</a> •
    <a href="https://github.com/djpeacher">GitHub</a> • <a href="/posts/index.xml">RSS</a></small>
  light:
    accent: '#212121'
    accentBg: '#f5f5f5'
  dark:
    accent: '#809fff'
