baseURL: http://www.djpeacher.com/
languageCode: en-us
title: Jonathan Peacher
theme: simple-hugo
description: Software Engineer • Coffee Enthusiast • Dungeon Master • Cat Dad
copyright: All work licensed under CC BY-SA 4.0 unless otherwise stated.
params:
  title: Jonathan Peacher
  subtitle: Software Engineer • Coffee Enthusiast • Dungeon Master • Cat Dad<br><a href="https://twitter.com/_djpeacher">Twitter</a> • <a href="https://fosstodon.org/@djpeacher">Mastadon</a> • <a href="https://github.com/djpeacher">GitHub</a>
  light:
    accent: '#212121'
    accentBg: '#f5f5f5'
  dark:
    accent: '#809fff'
menu:
  main:
    - name: Home
      pageref: /
      weight: 1
    - name: About
      pageref: /about
      weight: 2
    - name: Now
      pageref: /now
      weight: 3
