baseURL: 'http://www.djpeacher.com/'
languageCode: en-us
title: Jonathan Peacher
theme: simple-hugo
copyright: "Made with <i class='twa twa-red-heart'></i> by <a href='https://twitter.com/_djpeacher' target='_blank'>Jonathan Peacher</a><p><a href='/stats'>Stats for nerds</a></p>"
params:
  title: Jonathan Peacher <i class="twa twa-waving-hand-medium-light-skin-tone"></i>
  subtitle: Software Engineer • Coffee Enthusiast • Occasional DM • Cat Dad
  updateHeader: false
menu:
  footerTop:
    - name: Twitter
      url: https://twitter.com/_djpeacher
      weight: 1
    - name: GitHub
      url: https://github.com/djpeacher
      weight: 2
    - name: Resume
      url: /resume/
      weight: 3
