baseURL: http://www.djpeacher.com/
languageCode: en-us
title: Jonathan Peacher
theme: simple-hugo
description: Software Engineer • Coffee Enthusiast • Dungeon Master • Cat Dad
copyright: All work licensed under CC BY-SA 4.0 unless otherwise stated.
params:
  title: Jonathan Peacher <i class="twa twa-waving-hand-medium-light-skin-tone"></i>
  subtitle: Software Engineer • Coffee Enthusiast • Dungeon Master • Cat Dad
  replyEmail: reply@djpeacher.com
  light:
    accent: '#212121'
    accentBg: '#f5f5f5'
  dark:
    accent: '#809fff'
menu:
  main:
    - name: Home
      pageref: /
      weight: 1
    - name: About
      pageref: /about
      weight: 2
    - name: Now
      pageref: /now
      weight: 3
    - name: Code
      pageref: /code
      weight: 4
    - name: Twitter
      url: https://twitter.com/_djpeacher
      weight: 5
