baseURL: 'http://www.djpeacher.com/'
languageCode: en-us
title: Jonathan Peacher
theme: simple-hugo
copyright: "Made with <i class='twa twa-red-heart'></i> by <a href='https://twitter.com/_djpeacher' target='_blank'>Jonathan Peacher</a><p><a href='/stats'>Stats for nerds</a></p>"
params:
  title: Jonathan Peacher <i class="twa twa-waving-hand-medium-light-skin-tone"></i>
  subtitle: Software Engineer • Coffee Enthusiast • Occasional DM • Cat Dad
  dark:
    accent: '#809fff'
menu:
  main:
    - name: Home
      pageref: /
      weight: 1
    - name: Posts
      pageref: /posts
      weight: 2
    - name: About
      pageref: /about
      weight: 3
    - name: Contact
      pageref: /contact
      weight: 4
