name: Build
on:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - name: Install staticjinja
        run: pip install staticjinja
      - name: Switch & Pull
        run: git checkout site && git pull main --no-commit
      - name: Build Site
        run: staticjinja build
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Github Action: Built Site'
          branch: site
